FROM app
LABEL maintainer "Jérémie COLOMBO <jeremie.colombo@gmail.com>"

COPY run_tests.sh tests/id_rsa tests/* /

RUN set -x \
    && chmod +x /run_tests.sh \
    && chmod 400 /id_rsa

CMD ["/run_tests.sh"]