version: '2'
services:
  sut:
    build: .
    command: "/run_tests.sh"
    depends_on:
      - ftp
    volumes:
      - "data:/home"
      - "./tests/id_rsa:/id_rsa"
  ftp:
    image: stilliard/pure-ftpd:hardened
    environment:
      - "PUBLICHOST=ftp"
      - "FTP_USER_NAME=testuser"
      - "FTP_USER_PASS=testpasswd"
      - "FTP_USER_HOME=/home/ftp"
      - "ADDED_FLAGS=-S 0.0.0.0,29999"
    volumes:
      - "data:/home"
  sftp:
    image: amimof/sftp
    environment:
      - "SSH_USERNAME=sftpuser"
      - "SSH_PASSWORD=testpasswd"
    volumes:
      - "data:/home"
      - "./tests/id_rsa.pub:/home/sftpuser/.ssh/keys/id_rsa.pub"
volumes:
  data: