#!/bin/bash

echo "export BACKUP_SOURCE=$BACKUP_SOURCE
export MYSQL_HOST=$MYSQL_HOST
export MYSQL_PORT=$MYSQL_PORT
export MYSQL_USERNAME=$MYSQL_USERNAME
export MYSQL_PASSWORD=$MYSQL_PASSWORD
export FTP_HOST=$FTP_HOST
export FTP_PORT=$FTP_PORT
export FTP_PATH=$FTP_PATH
export FTP_USERNAME=$FTP_USERNAME
export FTP_PASSWORD=$FTP_PASSWORD
export SFTP_HOST=$SFTP_HOST
export SFTP_PORT=$SFTP_PORT
export SFTP_PATH=$SFTP_PATH
export SFTP_USERNAME=$SFTP_USERNAME
export SFTP_PASSWORD=$SFTP_PASSWORD
export SFTP_PRIVKEY=$SFTP_PRIVKEY
export OS_AUTH_URL=$OS_AUTH_URL
export OS_USERNAME=$OS_USERNAME
export OS_PASSWORD=$OS_PASSWORD
export OS_PROJECT_NAME=$OS_PROJECT_NAME
export OS_REGION_NAME=$OS_REGION_NAME
export OS_DELETE_AFTER=$OS_DELETE_AFTER
export OS_CONTAINER=$OS_CONTAINER
export OS_PATH=$OS_PATH" > ./env.sh